on:
  push:
    tags:
      - '**'
jobs:
  might_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
        name: Prepare release package
      - run: make release tag=${{  github.ref_name }}

      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{  github.ref_name }}
          files: build/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}